export const CASHIER_ALLOWED_PATHS = new Set([
  '/dashboard',
  '/phone-shop-pos',
  '/invoices',
  '/pos-billing/new-sale',
  '/per-order/add',
  '/per-order/list',
  '/products/add',
  '/products/list',
  '/products/barcode',
  '/inventory/low-stock-alert',
  '/inventory/transfer-stock',
  '/people/customers/add',
  '/sms',
]);
